application: nexus-camera
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
# Endpoints handler
- url: /_ah/spi/.*
  script: main.app

libraries:
- name: pycrypto
  version: latest
- name: endpoints
  version: 1.0